Milestone 3A - Holden Evers
hack4impact-calpoly/bootcamp-project-2023 pull request #142
Opened 2023-11-25 00:15 UTC by HoldenEv

## Developer: Holden Evers

Closes #140

### Pull Request Summary

created a rest api using MongoDB to all for the storage of the blog and project objects.

## Special Instructions (optional)

### Pull Request Checklist

- [X ] Code is neat, readable, and works
- [ X] Comments are appropriate
- [ X] The commit messages follows our [guidelines](https://h4i.notion.site/Conventional-Commits-593452ad1179489399ad3bd696ef772a)
- [X ] The developer name is specified
- [X ] The summary is completed
- [X ] Ask for a review in communication channels

### Screenshots/Screencast

2023-12-07 03:30 UTC, jlaksana requested changes
I think you forgot to push your milestone 3 code.

2024-01-09 05:39 UTC, ragdassi commented on bootcamp-milestone-3A/src/database/projectSchema.ts
> +// import IBlog from "@/blogData";
looks good

2024-01-09 05:41 UTC, ragdassi commented on bootcamp-milestone-3A/src/app/blog/page.tsx
> +  await connectDB();
nice job with the async function

2024-01-09 05:47 UTC, ragdassi commented on bootcamp-milestone-3A/src/app/portfolio/page.tsx
> +async function getProjects() {
nice work

2024-01-09 05:51 UTC, ragdassi commented
MS 3a looks great!

2024-01-09 05:51 UTC, closed without merging